import Image from 'next/image';import Link from 'next/link';import {Hero} from '@/components/sections/Hero';import {HorizontalCategories} from '@/components/sections/HorizontalCategories';import {Parallax} from '@/components/motion/Parallax';import {Reveal} from '@/components/motion/Reveal';import {GoldRule} from '@/components/motion/GoldRule';import {StaggerList,StaggerItem} from '@/components/motion/StaggerList';import {ProductCard} from '@/components/ui/ProductCard';import {products} from '@/lib/data';
export default function Home(){return <>
<Hero/>
<section className="category-intro section container"><span className="smallcaps">Jewelry, by form</span><div className="category-intro-head"><h2 className="display">Made to live<br/>against the skin.</h2><p>Rings, pendants, earrings, bracelets and necklaces in 18 and 22 karat gold. Each piece is made and hallmarked in Surat.</p></div><GoldRule/><Reveal className="statement"><p className="display">Varunyaa takes its name from <em>varenya</em> — the radiant, the worthy of being chosen. Gold shaped in conversation with the sun.</p></Reveal><GoldRule/></section>
<HorizontalCategories/>
<section className="craft"><Parallax strength={.12} className="craft-image"><Image src="/images/craft-hands.jpg" alt="A Varunyaa goldsmith hand-hammering a bangle in Surat" fill sizes="(max-width:900px) 100vw, 55vw" className="image-cover"/></Parallax><div className="craft-copy"><span className="smallcaps" style={{color:'#C6A15B'}}>Savoir-faire</span><h2 className="display">The mark<br/>of the hand.</h2><div className="craft-claim">22k gold alloyed for colour, not convenience.</div><div className="craft-claim">Raised, textured and finished at the bench.</div><div className="craft-claim">Hallmarked in India. Made to outlast its maker.</div><Link href="/savoir-faire" className="text-link" style={{marginTop:38,alignSelf:'flex-start'}}>Enter the atelier →</Link></div></section>
<section className="section container"><div className="products-head"><div><span className="smallcaps">Selected objects</span><h2 className="display">Pieces in light</h2></div><Link href="/collections" className="text-link">View all pieces →</Link></div><StaggerList className="product-grid">{products.map(p=><StaggerItem key={p.slug}><ProductCard product={p}/></StaggerItem>)}</StaggerList></section>
<section className="color-story"><div className="solar"><div className="solar-mark" aria-label="Varunyaa solar mark"/></div><Reveal className="color-copy"><span className="smallcaps">The colour of 22k</span><h2 className="display">Gold, nearly<br/>at its purest.</h2><p>At 91.6 percent purity, 22k gold keeps the depth and warmth that lower karats surrender. Its colour is not applied. It belongs to the metal.</p><p>Our alloy is balanced for a rich, unwavering yellow — then worked slowly, because gold this pure remembers every touch.</p></Reveal></section>
<section className="appointment"><div className="container appointment-inner"><h2 className="display">Every piece can be seen in person, or in a private video appointment.</h2><Link href="/appointments" className="text-link">Arrange a viewing →</Link></div></section>
</>}
